server:
    port: 8080
    context-path: /bi-master/v1

spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.21.190:3306/bi-master?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password:

mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.yunat.bi.domain

spring:
  freemarker:
    request-context-attribute: request